export const depotsData = [
  {
    id: 'DEP01',
    name: 'Swargate Depot',
    location: 'Swargate, Pune',
    vehicles: 42,
    drivers: 38,
    capacity: {
      vehicles: 45,
      drivers: 42,
    },
    status: 'operational',
    fuel: 78,
    routesCovered: 32,
    routesTotal: 40,
    nextDeparture: '15:30',
    lastActivity: 'MH-12-5847 on 401 at 14:28',
    alert: null,
  },
  {
    id: 'DEP02',
    name: 'Nigdi Depot',
    location: 'Nigdi, Pune',
    vehicles: 38,
    drivers: 34,
    capacity: {
      vehicles: 40,
      drivers: 38,
    },
    status: 'warning',
    fuel: 15,
    routesCovered: 28,
    routesTotal: 35,
    nextDeparture: '15:45',
    lastActivity: 'MH-12-6012 on 205 at 14:35',
    alert: 'Low fuel - Refill scheduled 15:00',
  },
  {
    id: 'DEP03',
    name: 'Bhosari Depot',
    location: 'Bhosari, Pune',
    vehicles: 25,
    drivers: 22,
    capacity: {
      vehicles: 28,
      drivers: 26,
    },
    status: 'operational',
    fuel: 65,
    routesCovered: 18,
    routesTotal: 25,
    nextDeparture: '16:00',
    lastActivity: 'MH-12-7234 on 156 at 14:40',
    alert: 'Maintenance: 3 buses in workshop (Est. 2 days)',
  },
  {
    id: 'DEP04',
    name: 'Katraj Depot',
    location: 'Katraj, Pune',
    vehicles: 13,
    drivers: 12,
    capacity: {
      vehicles: 14,
      drivers: 14,
    },
    status: 'operational',
    fuel: 82,
    routesCovered: 12,
    routesTotal: 15,
    nextDeparture: '16:15',
    lastActivity: 'MH-12-8901 on 302 at 14:42',
    alert: null,
  },
];
